# Use an official Node.js runtime as a parent image
FROM node:20-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and bun.lock files to the working directory
COPY backend/package.json backend/bun.lock* ./

# Install app dependencies
RUN bun install --frozen-lockfile

# Copy the rest of the application's code
COPY backend/ .

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD ["bun", "run", "start"]
