# ===== STAGE 1: BUILD =====
FROM oven/bun:1.2.22 AS build

WORKDIR /usr/src/app

COPY backend/package.json backend/bun.lock* ./
RUN bun install --frozen-lockfile

COPY backend/ .
RUN bun run build


# ===== STAGE 2: RUNTIME =====
FROM oven/bun:1.2.22 AS runtime

WORKDIR /usr/src/app

# Copia SOMENTE o resultado do build
COPY --from=build /usr/src/app ./

EXPOSE 3000
CMD ["bun", "dist/server.js"]
