services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    restart: always
    ports:
      - "3000:3000"
    env_file:
      - backend/.env 

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: https://file-upload-api-1bvr.onrender.com

    restart: always
    ports:
      - "80:80" 